version: '3.8'

services:
  dev:
    container_name: login_nest_dev
    image: login-nest-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229 
    command: npm run start:dev
    networks:
      - nesjs-network
    depends_on:
      - postgres_db
    volumes:
      - .:/usr/src/app
      - usr/src/app/node_modules
    restart: always
  prod:
    container_name: login_nest_prod
    image: login-nest-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  postgres_db:
    container_name: login_nest_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
networks:
  nesjs-network:
volumes:
  pgdata:
