name: nest-login-system builds
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test