name: nest-login-system builds
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
      - name: Build the stack
        run: docker-compose up -d test
      - name: Lint
        run: npm run lint